---
title: "My Webpage"
author: "Allen Bondurant"
date: "10/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Load in Packages
```{r packages, warning = FALSE, message = FALSE}
  library(leaflet)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(DT)
  library(sf)
  library(ggmap)
  library(cowplot)# devtools::install_github("dkahle/ggmap")
```

# Load Salmon Escapement Data

```{r}
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"

esc <- tryCatch(
    read.csv("data/escapement.csv", stringsAsFactors = FALSE),
    error=function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"), stringsAsFactors = FALSE)
        return(esc)
    }
)


```

# Calculate Annual Escapement by Species, Year, and Region

```{r, results = "hide"}
species_list <- c("Chinook", "Sockeye", "Chum", "Pink", "Coho")

annual_esc <- esc %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-", remove = FALSE) %>% 
  mutate(Year = as.numeric(Year)) %>% 
  group_by(Species, SASAP.Region, Year) %>% 
  summarize(Escapement = sum(DailyCount)) %>% 
  filter(Species %in% species_list)
  #filter(Species %in% c("Chinook", "Sockeye", "Chum", "Coho", "Pink"))

head(annual_esc)
```

# Visualize Escapement
##Total Escapement by Region and Species
```{r, echo = FALSE}
ggplot(data = annual_esc, mapping = aes(x = Species, y = Escapement, fill = SASAP.Region)) +
  geom_col()+
  theme_cowplot()
```
## Kodiak Escapement Over Time by Species

```{r}
ggplot(data = filter(annual_esc, SASAP.Region == "Kodiak"),
       mapping = aes(x = Year, y = Escapement, color = Species))+
  geom_point()+
  geom_line()+
  ylab("Escapement (no. fish)")+
  ggtitle("Kodiak Salmon Escapement")
```
## Escapement over time: all regions
```{r, fig.width = 7, fig.height = 12}
fig1 <- ggplot(annual_esc, aes(x = Year, y = Escapement, color = Species))+
  geom_point() +
  geom_line() +
  facet_wrap(~SASAP.Region, scales = "free_y", ncol = 1)

fig1

ggsave("escapement.png", fig1, width = 12, height = 7, units = "in")
```




# Map Sampling Locations

Create a table with unique sampling locations, latitudes, and longitudes



```{r}
locations <-esc %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()


head(locations)
```

```{r}
datatable(locations)
```

```{r}
leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(lng = ~Longitude, lat = ~Latitude)
```


```{r}
leaflet(locations) %>% 
  addWMSTiles("http://gis.dnr.alaska.gov/terrapixel/cubeserv/ortho?",
              layers = 'SDMI_ORTHO_RGB',
              attribution = "Imagery reproduced from the GINA BDL") %>%
  addCircleMarkers(lng = ~Longitude,
                   lat = ~Latitude,
                   popup = ~ Location,
                   radius = 5,
                   # set fill properties
                   fillColor = "salmon",
                   fillOpacity = 1,
                   # set stroke properties
                   stroke = T,
                   weight = 0.5,
                   color = "white",
                   opacity = 1)
```

